Repository btcven/locha, pull requests merged in 2020-06, with the labels that each got.

#121 Update readme
  README.md
  images/329px_281px_MoneroCommunity.png
Labels: Status: Ready for Review

#120 create AUTHORS file
  AUTHORS
Labels: Status: Ready for Review, Type: Documentation, urgent

#119 [dev] into [master]
  AUTHORS
  README.md
  crowdin.yml
  documentation/es/chapter_01.md
  documentation/es/chapter_02.md
  documentation/es/chapter_03.md
  documentation/es/chapter_04.md
  documentation/es/chapter_05.md
  documentation/es/chapter_06.md
  documentation/es/chapter_07.md
  documentation/es/chapter_08.md
  documentation/es/chapter_09.md
  documentation/es/chapter_10.md
  documentation/es/chapter_11.md
  documentation/es/chapter_12.md
  documentation/es/chapter_13.md
  documentation/es/chapter_14.md
  documentation/es/draft_modulators.md
  documentation/es/index.md
  documentation/es/references.md
  documentation/nl/chapter_01.md
  documentation/nl/chapter_02.md
  documentation/nl/chapter_03.md
  documentation/nl/chapter_04.md
  documentation/nl/chapter_05.md
  documentation/nl/chapter_06.md
  documentation/nl/chapter_07.md
  documentation/nl/chapter_08.md
  documentation/nl/chapter_09.md
  documentation/nl/chapter_10.md
  documentation/nl/chapter_11.md
  documentation/nl/chapter_12.md
  documentation/nl/chapter_13.md
  documentation/nl/chapter_14.md
  documentation/nl/draft_modulators.md
  documentation/nl/index.md
  documentation/nl/references.md
  images/329px_281px_MoneroCommunity.png
Labels: Status: Ready for Review, Type: Documentation

#123 merge [dev] into [master]
  AUTHORS
  README.md
Labels: Status: Ready for Review, Type: Documentation

#124 DIY hardware tutorial for the Locha Mesh
  documentation/en/anex_diy_turpial.md
  documentation/pics/basic_turpial.svg
  documentation/pics/diy.svg
  documentation/pics/diy_baby.svg
  documentation/pics/launchxl-cc1312r1_cc1312r1-top-prof1.jpg
  documentation/pics/radiocontrolli-cc1312r.jpg
Labels: Status: Ready for Review, Type: Documentation

#126 New Crowdin translations
  documentation/nl/anex_diy_turpial.md
Labels: Status: Ready for Review

#129 Update README
  README.md
Labels: Status: Ready for Review

#128 New Crowdin translations
  documentation/nl/diy_turpial.md
  documentation/nl/index.md
Labels: Status: Ready for Review

#131 New Crowdin translations
  documentation/fr/anex_diy_turpial.md
  documentation/fr/chapter_01.md
  documentation/fr/chapter_02.md
  documentation/fr/chapter_03.md
  documentation/fr/chapter_04.md
  documentation/fr/chapter_05.md
  documentation/fr/chapter_06.md
  documentation/fr/chapter_07.md
  documentation/fr/chapter_08.md
  documentation/fr/chapter_09.md
  documentation/fr/chapter_10.md
  documentation/fr/chapter_11.md
  documentation/fr/chapter_12.md
  documentation/fr/chapter_13.md
  documentation/fr/chapter_14.md
  documentation/fr/diy_turpial.md
  documentation/fr/draft_modulators.md
  documentation/fr/index.md
  documentation/fr/references.md
Labels: Status: Ready for Review
